### ISSUE TITLE
Implement jsonformer

### ISSUE THREAD

**Issue by itsbalamurali** [rustformers/llm#314] opened 2023-06-18 07:38 UTC
Implement jsonformer: https://github.com/1rgs/jsonformer

**Comment by philpax** [comment] 2023-06-18 08:35
Hi, thanks for requesting this! This is a duplicate of #235 (which is a more general issue), so I'm going to close this, but feel free to vote on that issue to prioritise it :)

**Closed by philpax** 2023-06-18 08:35 UTC

**Comment by pixelspark** [comment] 2023-06-25 15:03
I have an implementation of this using llm, basically it is a `dyn Sampler` you plug in. Can publish as a separate crate (and imho should not be part of `llm` core, although I like the idea in #235 of providing more hooks for guided generation).
